// Code generated by GoHT v0.8.3 - DO NOT EDIT.
// https://github.com/stackus/goht

package assets

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"fmt"
	"github.com/wolfmanjm/svd_web/gen/dbstore"
	"github.com/wolfmanjm/svd_web/internal/database"
)

func displayBits(numbits, offset int32) string {
	bs := offset
	be := offset + numbits - 1
	if bs == be {
		return fmt.Sprintf("[%v]", bs)
	}
	return fmt.Sprintf("[%v:%v]", be, bs)
}

func ShowFields(db *database.Database, fields []dbstore.Field) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		r := db.GetRegister(fields[0].RegisterID)
		p := db.GetPeripheral(r.PeripheralID)
		m := db.GetMpu(p.MpuID)
		if _, __err = __buf.WriteString("<header>\n<h1>Fields for "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(r.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" of "); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.EscapeString(p.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</h1>\n<p class=\"subtitle\">Reference Guide for "); __err != nil {
			return
		}
		var __var3 string
		if __var3, __err = goht.CaptureErrors(goht.EscapeString(m.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var3); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n</header>\n<div class=\"register-fields\">\n"); __err != nil {
			return
		}
		for _, f := range fields {
			if _, __err = __buf.WriteString("<div class=\"field\">\n<div class=\"field-bits\">"); __err != nil {
				return
			}
			var __var4 string
			if __var4, __err = goht.CaptureErrors(goht.EscapeString(displayBits(f.NumBits, f.BitOffset))); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var4); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</div>\n<div class=\"field-name\">"); __err != nil {
				return
			}
			var __var5 string
			if __var5, __err = goht.CaptureErrors(goht.EscapeString(f.Name)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var5); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</div>\n</div>\n"); __err != nil {
				return
			}
			if f.Description.Valid {
				if _, __err = __buf.WriteString("<div class=\"field-desc\">"); __err != nil {
					return
				}
				var __var6 string
				if __var6, __err = goht.CaptureErrors(goht.EscapeString(f.Description.String)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var6); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</div>\n"); __err != nil {
					return
				}
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
