// Code generated by GoHT v0.8.3 - DO NOT EDIT.
// https://github.com/stackus/goht

package assets

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"fmt"
	"github.com/wolfmanjm/svd_web/gen/dbstore"
	"github.com/wolfmanjm/svd_web/internal/database"
)

func ShowRegisters(db *database.Database, regs []dbstore.Register) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<header>\n"); __err != nil {
			return
		}
		p := db.GetPeripheral(regs[0].PeripheralID)
		m := db.GetMpu(p.MpuID)
		if _, __err = __buf.WriteString("<h1>Registers for "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(p.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</h1>\n<p class=\"subtitle\">Reference Guide for "); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.EscapeString(m.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n</header>\n<div class=\"search-bar\">\n<input id=\"searchInput\" name=\"pattern\" placeholder=\"Filter registers...\" type=\"search\" hx-get=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/findregisters/%d", p.ID)) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" hx-swap=\"outerHTML\" hx-target=\".registers\" hx-select=\".registers\" hx-include=\"[name=&#39;pattern&#39;]\"></div>\n<link_to class=\"backto-item\" hx-get=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/peripherals/%d", m.ID)) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" hx-swap=\"innerHTML\" hx-target=\"#contentArea.content\">Back to Peripherals</link_to>\n<div class=\"registers\">\n"); __err != nil {
			return
		}
		for _, r := range regs {
			name := r.Name
			if _, __err = __buf.WriteString("<div class=\"register\" hx-get=\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/fields/%d", r.ID)) + "\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(" hx-swap=\"innerHTML\" hx-target=\"#contentArea.content\">\n<span class=\"register-name\">"); __err != nil {
				return
			}
			var __var3 string
			if __var3, __err = goht.CaptureErrors(goht.EscapeString(name)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var3); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</span>\n<span class=\"register-offset\">Address Offset "); __err != nil {
				return
			}
			var __var4 string
			if __var4, __err = goht.CaptureErrors(goht.EscapeString(r.AddressOffset)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var4); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</span>\n"); __err != nil {
				return
			}
			if r.ResetValue.Valid {
				if _, __err = __buf.WriteString("<span class=\"register-offset\">Reset Value "); __err != nil {
					return
				}
				var __var5 string
				if __var5, __err = goht.CaptureErrors(goht.EscapeString(r.ResetValue.String)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var5); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</span>\n"); __err != nil {
					return
				}
			}
			if r.Description.Valid {
				if _, __err = __buf.WriteString("<br><span class=\"register-desc\">"); __err != nil {
					return
				}
				var __var6 string
				if __var6, __err = goht.CaptureErrors(goht.EscapeString(r.Description.String)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var6); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</span>\n"); __err != nil {
					return
				}
			}
			if _, __err = __buf.WriteString("</div>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
