// Code generated by GoHT v0.8.3 - DO NOT EDIT.
// https://github.com/stackus/goht

package assets

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"fmt"
	"github.com/wolfmanjm/svd_web/gen/dbstore"
	"github.com/wolfmanjm/svd_web/internal/database"
	"github.com/wolfmanjm/svd_web/internal/helpers"
)

func displayBits(numbits, offset int32) string {
	bs := offset
	be := offset + numbits - 1
	if bs == be {
		return fmt.Sprintf("[%v]", bs)
	}
	return fmt.Sprintf("[%v:%v]", be, bs)
}

func BitNumbersFrag(bs []helpers.BitField) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!--Bit numbers-->\n<tr class=\"bit-numbers\">\n"); __err != nil {
			return
		}
		for _, b := range bs {
			if b.Colspan > 1 {
				if _, __err = __buf.WriteString("<td colspan=\""); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(goht.EscapeString(goht.FormatString("%d", b.Colspan)) + "\""); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(">"); __err != nil {
					return
				}
				var __var1 string
				if __var1, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var1); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</td>\n"); __err != nil {
					return
				}
			} else {
				if _, __err = __buf.WriteString("<td>"); __err != nil {
					return
				}
				var __var2 string
				if __var2, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var2); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</td>\n"); __err != nil {
					return
				}
			}
		}
		if _, __err = __buf.WriteString("</tr>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}

func FieldNamesFrag(bs []helpers.BitField) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!--Field Names-->\n<tr class=\"bit-fields\">\n"); __err != nil {
			return
		}
		for _, b := range bs {
			if b.Colspan > 1 {
				if b.Reserved {
					if _, __err = __buf.WriteString("<td class=\"reserved\" colspan=\""); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(goht.EscapeString(goht.FormatString("%d", b.Colspan)) + "\""); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(">"); __err != nil {
						return
					}
					var __var1 string
					if __var1, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(__var1); __err != nil {
						return
					}
					if _, __err = __buf.WriteString("</td>\n"); __err != nil {
						return
					}
				} else {
					if _, __err = __buf.WriteString("<td class=\"rw\" colspan=\""); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(goht.EscapeString(goht.FormatString("%d", b.Colspan)) + "\""); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(">"); __err != nil {
						return
					}
					var __var2 string
					if __var2, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(__var2); __err != nil {
						return
					}
					if _, __err = __buf.WriteString("</td>\n"); __err != nil {
						return
					}
				}
			} else {
				if b.Reserved {
					if _, __err = __buf.WriteString("<td class=\"reserved\">"); __err != nil {
						return
					}
					var __var3 string
					if __var3, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(__var3); __err != nil {
						return
					}
					if _, __err = __buf.WriteString("</td>\n"); __err != nil {
						return
					}
				} else {
					if _, __err = __buf.WriteString("<td class=\"rw\">"); __err != nil {
						return
					}
					var __var4 string
					if __var4, __err = goht.CaptureErrors(goht.EscapeString(b.Value)); __err != nil {
						return
					}
					if _, __err = __buf.WriteString(__var4); __err != nil {
						return
					}
					if _, __err = __buf.WriteString("</td>\n"); __err != nil {
						return
					}
				}
			}
		}
		if _, __err = __buf.WriteString("</tr>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}

func generateTable(fields []dbstore.Field) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		bnums, bnames := helpers.GenerateFieldDiagram(fields)
		if _, __err = __buf.WriteString("<!--Bit numbers-->\n<tr class=\"bit-numbers\">\n"); __err != nil {
			return
		}
		if __err = BitNumbersFrag(bnums).Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</tr>\n<!--Field names-->\n<tr class=\"bit-fields\">\n"); __err != nil {
			return
		}
		if __err = FieldNamesFrag(bnames).Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</tr>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}

func ShowFields(db *database.Database, fields []dbstore.Field) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		r := db.GetRegister(fields[0].RegisterID)
		p := db.GetPeripheral(r.PeripheralID)
		m := db.GetMpu(p.MpuID)
		if _, __err = __buf.WriteString("<header>\n<h1>Bit Fields for "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(r.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" of "); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.EscapeString(p.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</h1>\n<p class=\"subtitle\">Reference Guide for "); __err != nil {
			return
		}
		var __var3 string
		if __var3, __err = goht.CaptureErrors(goht.EscapeString(m.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var3); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n</header>\n<link_to class=\"backto-item\" hx-get=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/registers/%d", p.ID)) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" hx-swap=\"innerHTML\" hx-target=\"#contentArea.content\">Back to Registers</link_to>\n<div class=\"register-diagram\">\n<table class=\"bit-field-table\">\n"); __err != nil {
			return
		}
		if __err = generateTable(fields).Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</table>\n</div>\n<div class=\"register-fields\">\n"); __err != nil {
			return
		}
		for _, f := range fields {
			if _, __err = __buf.WriteString("<div class=\"field\">\n<div class=\"field-bits\">"); __err != nil {
				return
			}
			var __var4 string
			if __var4, __err = goht.CaptureErrors(goht.EscapeString(displayBits(f.NumBits, f.BitOffset))); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var4); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</div>\n<div class=\"field-name\">"); __err != nil {
				return
			}
			var __var5 string
			if __var5, __err = goht.CaptureErrors(goht.EscapeString(f.Name)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var5); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</div>\n</div>\n"); __err != nil {
				return
			}
			if f.Description.Valid {
				if _, __err = __buf.WriteString("<div class=\"field-desc\">"); __err != nil {
					return
				}
				var __var6 string
				if __var6, __err = goht.CaptureErrors(goht.EscapeString(f.Description.String)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var6); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</div>\n"); __err != nil {
					return
				}
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
