// Code generated by GoHT v0.8.3 - DO NOT EDIT.
// https://github.com/stackus/goht

package assets

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"fmt"
	"github.com/wolfmanjm/svd_web/gen/dbstore"
	"github.com/wolfmanjm/svd_web/internal/database"
)

func ShowPeripherals(db *database.Database, periphs []dbstore.Peripheral) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<header>\n"); __err != nil {
			return
		}
		p := periphs[0]
		m := db.GetMpu(p.MpuID)
		if _, __err = __buf.WriteString("<h1>Peripherals</h1>\n<p class=\"subtitle\">Reference Guide for "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(m.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n</header>\n<div class=\"search-bar\">\n<input id=\"searchInput\" name=\"pattern\" placeholder=\"Filter peripherals...\" type=\"search\" hx-get=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/findperipherals/%d", p.MpuID)) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" hx-swap=\"outerHTML\" hx-target=\".peripherals\" hx-select=\".peripherals\" hx-include=\"[name=&#39;pattern&#39;]\"></div>\n<div class=\"peripherals\">\n"); __err != nil {
			return
		}
		for _, p := range periphs {
			name := p.Name
			if _, __err = __buf.WriteString("<div class=\"peripheral\" data-name=\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(goht.EscapeString(name) + "\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("></div>\n<div class=\"peripheral-header\" hx-get=\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(goht.EscapeString(fmt.Sprintf("/registers/%d", p.ID)) + "\""); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(" hx-swap=\"innerHTML\" hx-target=\"#contentArea.content\">\n<div>\n<span class=\"peripheral-name\">"); __err != nil {
				return
			}
			var __var2 string
			if __var2, __err = goht.CaptureErrors(goht.EscapeString(name)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var2); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</span>\n<span class=\"peripheral-address\">"); __err != nil {
				return
			}
			var __var3 string
			if __var3, __err = goht.CaptureErrors(goht.EscapeString(p.BaseAddress)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var3); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</span>\n"); __err != nil {
				return
			}
			if p.DerivedFromID.Valid {
				p2 := db.GetPeripheral(p.DerivedFromID.Int32)
				if _, __err = __buf.WriteString("<span class=\"peripheral-description\">Same as "); __err != nil {
					return
				}
				var __var4 string
				if __var4, __err = goht.CaptureErrors(goht.EscapeString(p2.Name)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var4); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</span>\n"); __err != nil {
					return
				}
			}
			if p.Description.Valid {
				if _, __err = __buf.WriteString("<br><span class=\"peripheral-description\">"); __err != nil {
					return
				}
				var __var5 string
				if __var5, __err = goht.CaptureErrors(goht.EscapeString(p.Description.String)); __err != nil {
					return
				}
				if _, __err = __buf.WriteString(__var5); __err != nil {
					return
				}
				if _, __err = __buf.WriteString("</span>\n"); __err != nil {
					return
				}
			}
			if _, __err = __buf.WriteString("</div>\n</div>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
